name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Restore artifact from the cache
        id: astro-cache-restore
        uses: actions/cache/restore@v5
        with:
          path: ./node_modules/.astro
          key: astro-cache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            astro-cache-${{ runner.os }}-

      - name: Build with Astro
        run: pnpm build

      - name: Save artifact to the cache
        if: ${{ steps.astro-cache-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: ./node_modules/.astro
          key: ${{ steps.astro-cache-restore.outputs.cache-primary-key }}
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist/
          include-hidden-files: true


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
